development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= "redis://#{Rails.application.credentials.dig(:redis, :host)}:6379/1" %>
  channel_prefix: lair_api_production
